services:
  api:
    container_name: api
    image: 'api-bot'
    environment:
      XDEBUG_MODE: coverage
    ports:
      - 9001:9001
    volumes:
      - ./:/usr/src/api
      - /var/run/php/php8.3-fpm.sock
      - /var:/usr/src/api/var
      - /vendor:/usr/src/api/vendor
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
  nginx:
    container_name: nginx
    image: 'nginx:latest'
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/api
      - /var/run/php/php8.3-fpm.sock
volumes:
  var:
  vendor:
