services:
  api:
    container_name: api
    image: 'api-bot'
    environment:
      XDEBUG_MODE: coverage
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/src/api
      - /var/run/php/php8.3-fpm.sock
      - /var:/usr/src/api/var
      - /vendor:/usr/src/api/vendor
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: 1
      PGADMIN_CSRF_TRUSTED_ORIGINS: 'http://localhost:5050'
    ports:
      - 5050:80
    depends_on:
      - postgres
  nginx:
    container_name: nginx
    image: 'nginx:latest'
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/api
      - /var/run/php/php8.3-fpm.sock
volumes:
  var:
  vendor:
